issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - perfsprint
        - usestdlibvars


linters:
  enable:
    - asasalint
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - gci
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocritic
    - gocyclo
    - gofumpt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nolintlint
    - noctx
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - tagalign
    - tenv
    - testifylint
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  fast: false

  govet:
    enable-all: true
    disable:
      - structtag

  gofumpt:
    extra-rules: true

  perfsprint:
    errorf: false
    strconcat: false
